### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by WtfJoke** [philongtran/kprog#1]
Was mir im ersten Blick in [MAXGUI](https://github.com/philongtran/kprog/blob/master/MAXGUI/src/Game.java) aufgefallen ist.

Der (grösstenteils) duplikate code in run() bzw. actionperformed() in Game. 
Kannst du das evt in eine Methode move(String movement) auslagern oder ist das zu mühsam/schwierig?

Alternativ kannst du auch run komplett löschen, da du es nicht mehr verwendest.

Wahrscheinlich schau ich nochmals drüber...

**Comment by philongtran** [comment]
removed
